tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "inverse-on-surface": "#283044",
              "on-error": "#690005",
              "inverse-primary": "#494bd6",
              "error": "#ffb4ab",
              "tertiary-container": "#009ada",
              "on-primary-container": "#0d0096",
              "on-tertiary-fixed": "#001e2f",
              "surface-container": "#171f33",
              "surface": "#0b1326",
              "on-tertiary-container": "#002d43",
              "primary": "#c0c1ff",
              "on-tertiary": "#00344d",
              "surface-container-high": "#222a3d",
              "primary-fixed": "#e1e0ff",
              "on-primary": "#1000a9",
              "on-background": "#dae2fd",
              "on-secondary-container": "#d6a9ff",
              "on-secondary-fixed": "#2c0051",
              "secondary-container": "#6f00be",
              "surface-container-lowest": "#060e20",
              "surface-bright": "#31394d",
              "background": "#0b1326",
              "tertiary-fixed": "#c9e6ff",
              "surface-container-low": "#131b2e",
              "on-surface-variant": "#c7c4d7",
              "surface-variant": "#2d3449",
              "on-secondary-fixed-variant": "#6900b3",
              "secondary-fixed": "#f0dbff",
              "primary-fixed-dim": "#c0c1ff",
              "surface-container-highest": "#2d3449",
              "on-tertiary-fixed-variant": "#004c6e",
              "tertiary-fixed-dim": "#89ceff",
              "secondary-fixed-dim": "#ddb7ff",
              "error-container": "#93000a",
              "surface-tint": "#c0c1ff",
              "on-surface": "#dae2fd",
              "outline": "#908fa0",
              "tertiary": "#89ceff",
              "secondary": "#ddb7ff",
              "inverse-surface": "#dae2fd",
              "on-error-container": "#ffdad6",
              "primary-container": "#8083ff",
              "on-primary-fixed": "#07006c",
              "on-secondary": "#490080",
              "surface-dim": "#0b1326",
              "on-primary-fixed-variant": "#2f2ebe",
              "outline-variant": "#464554"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "component-padding-x": "16px",
              "container-padding": "24px",
              "gutter": "16px",
              "base-unit": "4px",
              "component-padding-y": "12px",
              "section-gap": "80px"
      },
      "fontFamily": {
              "code-snippet": ["JetBrains Mono"],
              "body-base": ["Geist"],
              "display-lg-mobile": ["Plus Jakarta Sans"],
              "display-lg": ["Plus Jakarta Sans"],
              "label-sm": ["JetBrains Mono"],
              "headline-md": ["Plus Jakarta Sans"]
      },
      "fontSize": {
              "code-snippet": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
              "body-base": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "display-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "800"}],
              "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
              "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "600"}],
              "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "700"}]
      }
    },
  },
}
